git:
  depth: false
language: java
jdk:
  - openjdk11
services:
  - postgresql
  - docker
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git fetch
  - git config user.email "m.a.swertz@gmail.com"
  - git config user.name "Travis-CI"
  - git config url.https://.insteadOf git://
  - git checkout -qf $TRAVIS_BRANCH
install:
  - echo "skip default gradlew assemble"
before_script:
  - psql -c 'create database molgenis;' -U postgres
  - psql -c "CREATE USER molgenis WITH SUPERUSER PASSWORD 'molgenis';" -U postgres
  - psql -c "grant all privileges on database molgenis to molgenis;" -U postgres
addons:
  postgresql: "11.2"
  sonarcloud:
    organization: "mswertz-github"
script:
  - ./gradlew release jacocoMergedReport sonarqube shadowJar -Dorg.ajoberstar.grgit.auth.username=${GITHUB_TOKEN} -Dorg.ajoberstar.grgit.auth.password --info
