language: java
os: linux
dist: bionic
jdk:
  - openjdk11
services:
  - postgresql
  - docker
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git fetch
  - git config user.email "m.a.swertz@gmail.com"
  - git config user.name "Travis-CI"
  - git config url.https://.insteadOf git://
  - git checkout -qf $TRAVIS_BRANCH
install: skip
before_script:
  - psql -c 'create database molgenis;' -U postgres
  - psql -c "CREATE USER molgenis WITH SUPERUSER PASSWORD 'molgenis';" -U postgres
  - psql -c "grant all privileges on database molgenis to molgenis;" -U postgres
addons:
  postgresql: "11"
  sonarcloud:
    organization: "mswertz-github"
jobs:
  include:
    - stage: release
      script: ./gradlew jacocoMergedReport sonarqube --scan -s
    - # stage name not required, will continue to use `release`
      script: ./gradlew release shadowJar jib -Dorg.ajoberstar.grgit.auth.username=${GITHUB_TOKEN} -Dorg.ajoberstar.grgit.auth.password --scan -s
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  npm: true
  yarn: true
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/.gradle
    - .gradle

