language: java
services:
  - postgresql
before_script:
  - psql -c 'create database molgenis;' -U postgres
  - psql -c "CREATE USER molgenis WITH SUPERUSER PASSWORD 'molgenis';" -U postgres
  - psql -c "grant all privileges on database molgenis to molgenis;" -U postgres
addons:
  postgresql: "11.2"
  sonarcloud:
    organization: "mswertz-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mswertz_molgenis-emx2
after_success:
  - bash <(curl -s https://codecov.io/bash)

