language: java
services:
  - postgresql
before_script:
  - psql -c 'create database molgenis;' -U postgres
  - psql -c "CREATE USER molgenis WITH PASSWORD 'molgenis';" -U postgres
  - psql -c "grant all privileges on database molgenis to molgenis;" -U postgres
addons:
  sonarcloud:
    organization: "mswertz-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
env:
  global:
  - PGPORT=5433
