git:
  depth: false
language: java
jdk:
  - openjdk11
services:
  - postgresql
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_script:
  - psql -c 'create database molgenis;' -U postgres
  - psql -c "CREATE USER molgenis WITH SUPERUSER PASSWORD 'molgenis';" -U postgres
  - psql -c "grant all privileges on database molgenis to molgenis;" -U postgres
  - yarn global add @conveyal/maven-semantic-release semantic-release@15 @semantic-release/exec
addons:
  postgresql: "11.2"
  sonarcloud:
    organization: "mswertz-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mswertz_molgenis-emx2
after_success:
  - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release,@semantic-release/exec --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release,@semantic-release/exec --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch=dev --skip-maven-deploy
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn-cache
