language: java
services:
  - postgresql
before_script:
  - psql -p 5433 -c 'create database molgenis;' -U postgres
  - psql -p 5433 -c "CREATE USER molgenis WITH PASSWORD 'molgenis';" -U postgres
addons:
  sonarcloud:
    organization: "mswertz-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
