version: "3.0"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    expose:
      - "5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
  emx2:
    image: mswertz/emx2
    command: jdbc:postgresql://postgres/molgenis
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

