{{- if .Values.ingress.enabled }}
  {{- $fullName := include "emx2.fullname" . -}}
apiVersion: extensions/v1
kind: Ingress
metadata:
  name: {{ include "emx2.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: 8088
  {{- end }}
  {{- if .tls }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ .name }}
      {{- end }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
---
{{- end }}
