apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "emx2.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ include "emx2.fullname" . }}
              servicePort: 8088
